In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

In [2]:
df1 = pd.read_csv("Country-data.csv")
df2 = pd.read_csv("creditcard.csv")

In [3]:
df1.head()

country  child_mort  exports  health  imports  income  \
0          Afghanistan        90.2     10.0    7.58     44.9    1610   
1              Albania        16.6     28.0    6.55     48.6    9930   
2              Algeria        27.3     38.4    4.17     31.4   12900   
3               Angola       119.0     62.3    2.85     42.9    5900   
4  Antigua and Barbuda        10.3     45.5    6.03     58.9   19100   

   inflation  life_expec  total_fer   gdpp  
0       9.44        56.2       5.82    553  
1       4.49        76.3       1.65   4090  
2      16.10        76.5       2.89   4460  
3      22.40        60.1       6.16   3530  
4       1.44        76.8       2.13  12200

In [4]:
df2.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [5]:
np.unique(df2["Class"].values)

array([0, 1], dtype=int64)

In [6]:
df11 = df2[df2.columns[1:]]
df21 = df2[df2.columns[:-1]]

In [7]:
X1 = df11.values
X2 = df21.values

In [8]:
X1.shape, X2.shape

((284807, 30), (284807, 30))

Country Data for k = 2

In [9]:
model = KMeans(n_clusters=2, n_init=4, verbose=1, max_iter=3)

In [10]:
model.fit(X1)

Initialization complete
Iteration 0, inertia 15355477175.982346
Iteration 1, inertia 11029741483.103212
Iteration 2, inertia 10392052620.156
Initialization complete
Iteration 0, inertia 11114980702.64728
Iteration 1, inertia 9264719549.548733
Iteration 2, inertia 9102721435.752607
Initialization complete
Iteration 0, inertia 12335933988.245417
Iteration 1, inertia 10054582314.42063
Iteration 2, inertia 9625872693.42902
Initialization complete
Iteration 0, inertia 12731282274.103073
Iteration 1, inertia 10247849537.812023
Iteration 2, inertia 9758780502.942104


KMeans(max_iter=3, n_clusters=2, n_init=4, verbose=1)

In [11]:
model.cluster_centers_

array([[ 3.26057855e-02,  5.76572977e-02,  2.51826835e-02,
        -1.17976378e-02,  3.44565898e-02, -1.85262634e-02,
        -3.69604248e-02,  9.59436742e-03,  3.28556924e-03,
         7.94181926e-03, -7.87280491e-04,  8.33871426e-04,
        -5.53236011e-04, -3.21306631e-03, -6.21150418e-04,
        -1.23735478e-03, -3.89169934e-04, -1.20998738e-03,
         3.51151916e-03, -2.11103215e-02, -6.01010005e-03,
         4.99521799e-03,  6.32069988e-03, -7.33291634e-04,
         2.19754330e-03, -1.24054131e-04, -3.76137105e-04,
        -9.19022240e-04,  7.06226133e+01,  1.71319122e-03],
       [-3.19518565e+00, -5.65009452e+00, -2.46776293e+00,
         1.15610289e+00, -3.37655418e+00,  1.81547079e+00,
         3.62191609e+00, -9.40194650e-01, -3.21967514e-01,
        -7.78254120e-01,  7.71491098e-02, -8.17147623e-02,
         5.42140524e-02,  3.14862629e-01,  6.08692865e-02,
         1.21253887e-01,  3.81364892e-02,  1.18572034e-01,
        -3.44109348e-01,  2.06869410e+00,  5.88956381e-

In [12]:
model.inertia_

8993108022.120855

Credit Card Data for k = 2

In [13]:
model = KMeans(n_clusters=2, n_init=4, verbose=1, max_iter=3)
model.fit(X2)

Initialization complete
Iteration 0, inertia 133197499804769.97
Iteration 1, inertia 118387122772311.6
Iteration 2, inertia 118320729057132.44
Converged at iteration 2: center shift 4116.304743573539 within tolerance 7517.262262351321.
Initialization complete
Iteration 0, inertia 217397134618389.03
Iteration 1, inertia 119969342982985.11
Iteration 2, inertia 118332620375948.28
Initialization complete
Iteration 0, inertia 186568546424018.4
Iteration 1, inertia 119451025740449.81
Iteration 2, inertia 118329474501541.7
Initialization complete
Iteration 0, inertia 179793823891819.7
Iteration 1, inertia 118406789111879.89
Iteration 2, inertia 118323452868119.0


KMeans(max_iter=3, n_clusters=2, n_init=4, verbose=1)

In [14]:
model.cluster_centers_

array([[ 1.41083313e+05,  2.73767049e-01, -5.15444169e-02,
        -7.06911008e-01, -1.55103617e-01,  2.79380502e-01,
        -8.09820247e-02,  1.21060177e-01, -6.12691562e-02,
         4.03453498e-02,  3.45519063e-02, -2.43862400e-01,
         3.77698228e-02, -3.37779537e-02, -6.54987759e-02,
        -2.12086853e-01,  1.37932481e-02, -5.10405524e-02,
         8.24898455e-02,  2.46551972e-02, -4.59766665e-02,
         4.32965774e-02,  1.27668887e-01,  3.32715680e-02,
        -1.36283144e-02, -1.35737230e-01, -2.67064777e-02,
        -2.18643134e-03, -3.32139465e-03,  8.80042894e+01],
       [ 5.50524450e+04, -2.35260292e-01,  4.42944270e-02,
         6.07480303e-01,  1.33287488e-01, -2.40084184e-01,
         6.95914823e-02, -1.04032434e-01,  5.26513312e-02,
        -3.46705668e-02, -2.96920012e-02,  2.09561887e-01,
        -3.24573010e-02,  2.90269091e-02,  5.62860329e-02,
         1.82255736e-01, -1.18531561e-02,  4.38614336e-02,
        -7.08872202e-02, -2.11873157e-02,  3.95098096e-

In [15]:
model.inertia_

118320095020223.72

Country Data for k = 5

In [16]:
model = KMeans(n_clusters=5, n_init=4, verbose=1, max_iter=3)
model.fit(X1)

Initialization complete
Iteration 0, inertia 2889028093.155498
Iteration 1, inertia 2717269558.1921086
Iteration 2, inertia 2704110391.975314
Initialization complete
Iteration 0, inertia 3295333163.6207714
Iteration 1, inertia 2869522403.4372406
Iteration 2, inertia 2832973997.1933174
Initialization complete
Iteration 0, inertia 3025270588.6172094
Iteration 1, inertia 2909840001.0567784
Iteration 2, inertia 2874583597.3048234
Initialization complete
Iteration 0, inertia 3040410093.5436487
Iteration 1, inertia 2717410920.4940886
Iteration 2, inertia 2693101368.7125025


KMeans(max_iter=3, n_clusters=5, n_init=4, verbose=1)

In [17]:
model.cluster_centers_

array([[ 9.83651344e-02,  2.54103108e-01,  6.04003529e-02,
        -1.70041712e-02,  1.27166399e-01, -6.45736185e-02,
        -8.38463653e-02,  2.53674301e-02,  1.18147742e-02,
         2.45559224e-02,  5.11664845e-03, -5.22905530e-03,
         6.41475476e-03, -4.40675480e-03,  1.05158842e-02,
         2.29428429e-02, -4.59008062e-03, -1.39598504e-02,
         1.08309624e-02, -5.92953649e-02, -1.97182136e-02,
         1.03818799e-03,  6.74124616e-03,  2.97953032e-03,
         1.75356983e-03, -1.64555584e-03,  2.97617850e-03,
        -1.46491495e-03,  3.16655816e+01,  1.59640849e-03],
       [-3.70843022e+00, -6.38774863e+00, -2.80870489e+00,
         1.32446444e+00, -3.81013619e+00,  2.09938947e+00,
         4.12031962e+00, -1.12419876e+00, -2.94638143e-01,
        -8.68205805e-01,  4.89664347e-02, -9.68806826e-02,
         9.78763645e-02,  3.40398805e-01,  9.45513707e-02,
         1.77688719e-01,  4.07348875e-02,  1.55725960e-01,
        -4.07262315e-01,  2.37250672e+00,  7.02706113e-

In [18]:
model.inertia_

2686047237.9081864

Credit Card Data for k = 5